name: accel_key
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  ubuntu_localizations: ^0.3.4

dev_dependencies:
  ffigen: ^7.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
