name: accel_key
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  ubuntu_localizations: ^0.1.6

dev_dependencies:
  ffigen: ^8.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
