name: title_bar
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: # TODO: ^0.2.9
    git:
      ref: b8188c800928afdbcec1dc0ff3e680c466e9a053
      url: https://github.com/leanflutter/window_manager
  yaru_icons: ^1.0.0
  yaru_widgets: # TODO: ^2.0.0
    git:
      url: https://github.com/ubuntu/yaru_widgets.git
      ref: d2439368841f4d7ab386db102a84d1330d7ac59e

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
