name: jsettings_example
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  jsettings:
    path: ../
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  yaru: ^0.4.3

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
