name: flutter_jsettings
description: JSON settings
homepage: https://github.com/ubuntu-flutter-community/jsettings.dart
repository: https://github.com/ubuntu-flutter-community/jsettings.dart
issue_tracker: https://github.com/ubuntu-flutter-community/jsettings.dart/issues
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  jsettings: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
