name: jsettings
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  path: ^1.8.0
  watcher: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.16.0
