name: workshops
description: Workshops
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  accel_key:
    path: packages/accel_key
  async_value:
    path: packages/async_value
  collection: ^1.15.0
  command_palette:
    git:
      ref: scroll-to-highlighted-action
      url: https://github.com/jpnurmi/command_palette.git
  command_store:
    path: packages/command_store
  context_menu:
    path: packages/context_menu
  data_size: ^0.2.0
  data_table_2: ^2.3.8
  fake_async: ^1.3.1
  flutter:
    sdk: flutter
  flutter_jsettings: ^0.1.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  freezed_annotation: ^2.0.3
  handy_window: ^0.2.0
  intl: ^0.18.0
  jsettings: ^0.1.1
  json_annotation: ^4.5.0
  lxd:
    path: packages/lxd
  lxd_service:
    path: packages/lxd_service
  lxd_test:
    path: packages/lxd_test
  lxd_x:
    path: packages/lxd_x
  meta: ^1.7.0
  movable_tabs:
    path: packages/movable_tabs
  nested_split_view:
    path: packages/nested_split_view
  os_logo:
    path: packages/os_logo
  osarch:
    path: packages/osarch
  path: ^1.8.2
  petname:
    path: packages/petname
  provider: ^6.0.3
  safe_change_notifier: ^0.2.0
  simplestreams:
    git:
      url: https://github.com/canonical/simplestreams.dart
      ref: 9a55c5ff1fa545d4d95ded509d2ac7e81ea1d296
  substring_highlight: ^1.0.33
  terminal_view:
    path: packages/terminal_view
  ubuntu_localizations: ^0.1.6
  ubuntu_logger: ^0.0.1
  ubuntu_service: ^0.2.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
      ref: 2549b38607f8c634404f478f719a6ab6a5344605
  window_manager: ^0.3.0
  wizard_router: ^0.9.0
  xdg_directories: ^0.2.0+2
  yaml: ^3.1.1
  yaru: ^0.5.0
  yaru_icons: ^1.0.0
  yaru_widgets: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.1
  json_serializable: ^6.2.0
  melos: ^3.0.1
  mockito: 5.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
