name: terminal_view
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: 9ab11f5f112c5012c9748ec8a138466452336210
  xterm:
    git:
      url: https://github.com/jpnurmi/xterm.dart
      ref: eb462568e75b7329bb7401095a7f3d1ff1e8c21d

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
