name: nested_split_view
description: Nested SplitView.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  split_view: ^3.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
