name: command_store
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  accel_key:
    path: ../accel_key
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_jsettings: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.5
