name: gtk_accelerator
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  hotkey_manager: ^0.1.7
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^7.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
