name: lxd
version: 0.0.6

description: |
  Provides a client to access lxd, which allows you to manage containers on a Linux system.

homepage: https://github.com/canonical/lxd.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.3.1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mockito: 5.4.0
  test: ^1.16.8
