name: lxd_test
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: 48f586befd7a4229ccf2b25b7b6e7590214db03d

dev_dependencies:
  lints: ^2.0.0
