name: osarch
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  meta: ^1.7.0
  stdlibc: ^0.1.0

dev_dependencies:
  mockito: ">=5.4.0 <5.5.0"
  test: ^1.21.1
