name: context_menu
description: Context menu.
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
