name: lxd_x
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: db51ab2d9a28bb6cef319bd86b12f00b3814355e

dev_dependencies:
  lints: ^2.0.0
