name: lxd_x
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: 40c6c4b4d6575850ac27b7ab789c01043d5e59f8

dev_dependencies:
  lints: ^2.0.0
