name: settings_store
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jsettings:
    git:
      url: https://github.com/ubuntu-flutter-community/jsettings.dart
      ref: 9a040b93d1c0a48307e2ab0518beb59a9e6aea12

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
