name: workshops
version: git
summary: Workshops
description: |
  Workshops provides a user friendly interface to create and manage LXD containers as well as provides a full featured terminal.
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
assumes:
  - snapd2.46

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  workshops:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  workshops:
    command: bin/workshops
    desktop: bin/data/flutter_assets/assets/workshops.desktop
    extensions: [gnome]
    plugs:
      - lxd
      - network
