name: lxd_service
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  lxd:
    path: ../lxd
  lxd_test:
    path: ../lxd_test
  lxd_x:
    path: ../lxd_x
  meta: ^1.8.0
  rxdart: ^0.27.3
  stdlibc: ^0.1.0
  ubuntu_logger: ^0.0.1

dev_dependencies:
  build_runner: ^2.1.11
  freezed: 2.2.1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mockito: 5.3.2
  test: ^1.16.0
