name: Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  flutter-version: '3.24.x'
jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
      - run: flutter pub global activate melos
      - run: melos pub-get
      - run: melos run analyze

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
      - run: flutter pub global activate melos
      - run: melos pub-get
      - run: melos run format

  pub:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
      - run: flutter pub global activate melos
      - run: melos pub-get
      - run: melos exec --no-private -- \
          flutter pub publish --dry-run
