name: Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: melos exec -- flutter pub get
      - run: melos run analyze

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: melos exec -- flutter pub get
      - run: melos run format

  pub:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: melos exec -- flutter pub get
      - run: melos exec --no-private -- \
          flutter pub publish --dry-run
