name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.x'
    - run: flutter pub global activate melos
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos pub-get
    - run: melos build

  snap:
    if: ${{false}}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.0.1'
    - run: dart pub global activate melos
    - run: sudo snap install --classic flutter
    - run: flutter doctor
    - run: melos pub-get
    - run: melos build
