name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  flutter-version: '3.24.x'
jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.flutter-version }}
    - run: flutter pub global activate melos
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos pub-get
    - run: melos build

  snap:
    if: ${{false}}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.5.4'
    - run: dart pub global activate melos
    - run: sudo snap install --classic flutter
    - run: flutter doctor
    - run: melos pub-get
    - run: melos build
