name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: dart pub get
      - run: flutter pub get
        working-directory: example
      - run: dart analyze --fatal-infos .

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: flutter build linux
      working-directory: example

  coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter config --enable-linux-desktop
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  format:
    runs-on: ubuntu-22.04
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v3
      - run: dart pub get
      - run: dart format --set-exit-if-changed .

  pub:
    runs-on: ubuntu-22.04
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v3
      - run: dart pub get
      - run: dart pub publish --dry-run

  test:
    runs-on: ubuntu-22.04
    container:
      image: dart:stable
    steps:
    - uses: actions/checkout@v3
    - run: dart pub get
    - run: dart test
